### ISSUE TITLE
Exporter should sanity-check and output something

### ISSUE THREAD

**Issue by jfautley** [jamesog/aaisp-chaos#1]
The `aaisp_exporter` command provides no output, and should sanity check the correct environment variables are configured.

This would make the experience for the end user significantly more interesting and make troubleshooting easier. 😄

**Comment by jamesog** [comment]
Done in cab8f1f6264ea8fe51b149e4eae354d75a5126be and 16d476249d214900dd4e35962fb4273faa3cdff0
